{
 "title": "REDES SESCAB",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "ROTEADORES",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "PING" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/MK - (.*): PING/",
        "$1"
       ],
       "text": "replaceAlias(/MK - (.*): PING/, $1)"
      }
     ],
     "group": { "filter": "Roteadores" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "PING" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PONTO ELETRONICO",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "PING" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/MK - (.*): PING/",
        "$1"
       ],
       "text": "replaceAlias(/MK - (.*): PING/, $1)"
      }
     ],
     "group": { "filter": "Roteadores" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "PING" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PREDIOS SESCAB",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 19, "w": 5, "x": 9, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "PING" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/MK - (.*): PING/",
        "$1"
       ],
       "text": "replaceAlias(/MK - (.*): PING/, $1)"
      }
     ],
     "group": { "filter": "Roteadores" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "PING" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SISTEMAS",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/WEB(.*): ICMP ping/",
        "$1"
       ],
       "text": "replaceAlias(/WEB(.*): ICMP ping/, $1)"
      }
     ],
     "group": { "filter": "sistema" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SERVIDORES",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 4, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/SRV (.*): ICMP ping/",
        "$1"
       ],
       "text": "replaceAlias(/SRV (.*): ICMP ping/, $1)"
      }
     ],
     "group": { "filter": "Servidores" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "IMPRESSORAS",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Disponibilidade do Equipamento"
     },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/impressora(.*): Ping/",
        "$1"
       ],
       "text": "replaceAlias(/impressora(.*): Ping/, $1)"
      }
     ],
     "group": { "filter": "IMPRESSORAS" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "Ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SESCAB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Discovery Network" },
     "group": { "filter": "Roteadores" },
     "host": { "filter": "MK - SESCAB" },
     "item": { "filter": "/.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "HOSPITAL",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Discovery Network" },
     "group": { "filter": "Roteadores" },
     "host": { "filter": "MK - HOSPITAL" },
     "item": { "filter": "/.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "POLICLINICA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Discovery Network" },
     "group": { "filter": "Roteadores" },
     "host": { "filter": "MK - POLICLINICA" },
     "item": { "filter": "/.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}